### PR TITLE
Drop unused IsOSImage variable in stateBag

### PR DESCRIPTION
**Pull request by shalupov**
It fails on https://github.com/MSOpenTech/packer-azure/blob/86e4e8392d07bf123c55dfe4e769a9878bfaee24/packer/builder/azure/win/step_set_provision_infrastructure.go#L71 otherwise

### CODE REVIEW

**Comment by paulmey** [comment]
LGTM, thanks for the clean up! :-)

**Comment by paulmey** [comment]
Can you please rebase this? Thanks, Paul

**Comment by shalupov** [comment]
Done

**Comment by paulmey** [comment]
Thanks!

**Pull request merged**
